# Generated by Django 5.2.1 on 2025-06-01 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('revoke', 'Revoked'), ('suspend', 'User Suspended'), ('unsuspend', 'User Unsuspended'), ('delete_course', 'Deleted Course')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('target_repr', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
