# Generated by Django 5.2.1 on 2025-06-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Approved'), ('revoke', 'Revoked'), ('suspend', 'User Suspended'), ('unsuspend', 'User Unsuspended'), ('delete_course', 'Deleted Course'), ('promote_to_staff', 'Promotion'), ('demote_from_staff', 'Demotion')], max_length=20),
        ),
    ]
