# Generated by Django 5.2.1 on 2025-05-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='timeout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
