# Generated by Django 5.2.1 on 2025-05-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_is_approved_lesson_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_approved',
        ),
    ]
