# Generated by Django 5.2.1 on 2025-05-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_virustotalscan_lesson_video_scan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('FB', 'Fill in the Blank')], max_length=3),
        ),
    ]
