# Generated by Django 5.2.1 on 2025-07-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_quiz_max_attempts_quiz_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_scan_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='file_scan_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
