# Generated by Django 5.2.1 on 2025-07-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_lesson_video_scan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('unsafe', 'Unsafe'), ('error', 'Error')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='lessonfile',
            name='file_scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('unsafe', 'Unsafe'), ('error', 'Error')], default='pending', max_length=10),
        ),
    ]
