# Generated by Django 5.2.1 on 2025-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_lesson_video_scan_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('malicious', 'Malicious'), ('error', 'Error')], default='pending', max_length=10),
        ),
    ]
